Update de1_soc according to instructions
yuri-panchul/basics-graphics-music pull request #129
Opened 2024-08-05 04:41 UTC by samedhi

```
1. Add additional parameters:

parameter clk_mhz = 100,
pixel_mhz = 25,

w_key = 5,
...
w_gpio = 32,

screen_width = 640,
screen_height = 480,

w_red = 4,
w_green = 4,
w_blue = 4,

w_x = $clog2 ( screen_width ),
w_y = $clog2 ( screen_height )
..

2. Add wire declarations

wire [w_x - 1:0] x;
wire [w_y - 1:0] y;

3. Change top -> lab_top module and instance name and propagate parameters
for graphics. Remove pixel_mhz propagation if present.

lab_top
.clk_mhz ( clk_mhz ),

.w_key ( w_key ),
...
.w_gpio ( w_gpio ),

.screen_width ( screen_width ),
.screen_height ( screen_height ),

.w_red ( w_red ),
.w_green ( w_green ),
.w_blue ( w_blue )
)
i_lab_top

4. Add instance port connections

.x ( x ),
.y ( y ),

5. Remove VGA-specific signals from port connection to lab_top instance

.vsync ( Vsync ),
.hsync ( Hsync ),

6. Rename to point to new board config

`include "lab_specific_board_config.svh"
```

2024-08-05 04:42 UTC, samedhi commented
Turns out I don't have a VGA monitor. So this is unknown in terms of VGA compatibility. Checked that first lab worked however.

2024-08-05 04:47 UTC, yuri-panchul commented
Great, thank you, Steve, I will review it. If you live nearby (I live in 
Sunnyvale) you can pick it at my house, I can loan you a monitor, I have 
an extra.

On 2024-08-04 22:42, Stephen Cagle wrote:

> Turns out I don't have a VGA monitor. So this is unknown in terms of 
> VGA compatibility. Checked that first lab worked however.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/yuri-panchul/basics-graphics-music/pull/129#issuecomment-2268160829
[2] 
https://github.com/notifications/unsubscribe-auth/AC6OFWSDAPB45WPFTC36DSDZP37EDAVCNFSM6AAAAABL7QL4I6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRYGE3DAOBSHE

2024-08-05 18:22 UTC, yuri-panchul commented on boards/de1_soc/board_specific_top.sv
> +              screen_width = 640,
Here I would prefer better space alignment, but it's OK for now - I will straighten it

2024-08-05 18:25 UTC, yuri-panchul commented on boards/de1_soc/board_specific_top.sv
>          .green    (   vga_green_4b       ),
You forgot to move the instance of VGA controller module here. Look at DE2-115:
basics-graphics-music/boards/de2_115/board_specific_top.sv

   //------------------------------------------------------------------------

    `ifdef INSTANTIATE_GRAPHICS_INTERFACE_MODULE

        wire [9:0] x10; assign x = x10;
        wire [9:0] y10; assign y = y10;

        vga
        # (
            .CLK_MHZ     ( clk_mhz   ),
            .PIXEL_MHZ   ( pixel_mhz )
        )
        i_vga
        (
            .clk         ( clk       ),
            .rst         ( rst       ),
            .hsync       ( VGA_HS    ),
            .vsync       ( VGA_VS    ),
            .display_on  (           ),
            .hpos        ( x10       ),
            .vpos        ( y10       ),
            .pixel_clk   ( VGA_CLK   )
        );

        assign VGA_BLANK_N = 1'b1;
        assign VGA_SYNC_N  = 1'b0;

    `endif

2024-08-05 18:26 UTC, yuri-panchul requested changes
See the comments

You forgot to move the instance of VGA controller module here. Look at DE2-115:
basics-graphics-music/boards/de2_115/board_specific_top.sv

//------------------------------------------------------------------------

`ifdef INSTANTIATE_GRAPHICS_INTERFACE_MODULE

    wire [9:0] x10; assign x = x10;
    wire [9:0] y10; assign y = y10;

    vga
    # (
        .CLK_MHZ     ( clk_mhz   ),
        .PIXEL_MHZ   ( pixel_mhz )
    )
    i_vga
    (
        .clk         ( clk       ),
        .rst         ( rst       ),
        .hsync       ( VGA_HS    ),
        .vsync       ( VGA_VS    ),
        .display_on  (           ),
        .hpos        ( x10       ),
        .vpos        ( y10       ),
        .pixel_clk   ( VGA_CLK   )
    );

    assign VGA_BLANK_N = 1'b1;
    assign VGA_SYNC_N  = 1'b0;

`endif

2024-08-09 18:48 UTC, yuri-panchul commented
VGA instance can be added later

2024-08-09 18:48 UTC, merged