Add switch controller for tm1638
yuri-panchul/basics-graphics-music pull request #154
Opened 2024-09-20 09:06 UTC by unaimillan

The module for TM1638 extension board that changes behaviour of the keys on the board to the switches

2024-09-20 16:02 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +			  W_TM_KEY = `W_TM_KEY
Зачем использовать одновременно и `W_TM_KEY, и W_TM_KEY? Какая схема использования? Параметр переписывает параметр по умолчанию заданный `define?

2024-09-20 16:03 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +			  W_TM_KEY = `W_TM_KEY
Похоже по смещению пробелов что тут прокралась табуляция

2024-09-20 16:06 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    logic [    W_TM_KEY - 1:0] switches, switches_d;
Весь этот код эквивалентен следующему. generate и побитовые опеции в цикле не нужны:

    always_ff @(posedge clk or posedge rst)
        if (rst)
            switches <= '0;
        else
            switches <= switches ^ tm_keys;

2024-09-20 16:11 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    input        [               7:0] ledr,
ledr не используется

2024-09-20 16:13 UTC, yuri-panchul requested changes
См. комменты

2024-09-21 13:47 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    input        [               7:0] ledr,
Это не "совместимость", это "ложная совместимость". Мы конструируем устройство с другим функционалом, которое реализует switches и не реализует контролируемые юзером led. Приделывать input led и называть switches - keys - это как приделывать лошадиные ноги к автомобилю.

2024-09-21 13:51 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    assign keys = switches;
Лишний сигнал, будет error в разных тулах

2024-09-21 13:54 UTC, unaimillan commented on peripherals/tm1638_switch.sv
> +    assign keys = switches;
Да, только что поправил.

2024-09-21 13:55 UTC, unaimillan commented
Исправил проблемы компиляции модуля. Так же обнаружил, что в плате `de10_lite_tm1638_arduino` убрали модуль tm1638

2024-09-21 14:00 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +`ifdef HCW132
HCW132 никогда использоваться не будет c данной конфигурацией, потому что в нем нет led.

Так что тут стоит поставить:

`ifdef HCW132
    `error_HCW132_is_not_compatible_with_tm1638_switches_module
`endif

После чего спокойно делать w_key параметром.

2024-09-21 14:02 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +)
",)" выдаст syntax error в некоторых тулах.

тут стоит поставить параметр w_key = 8

2024-09-21 14:04 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    logic [   `W_TM_KEY - 1:0] tm_keys_r;
Лишние пробелы после [.
Префикс tm_ здесь не несет никакой функциональной нагрузки, его можно опустить

2024-09-21 14:06 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    assign tm_leds = switches[7:0];
Зачем этот дублированный сигнал? И тем более с [7:0]? Мы передаем на led в tm подмодуль текущее состояние switches

2024-09-21 14:06 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +            tm_keys_r <= '0;
Нужно выровнять два <= для легкости чтения

2024-09-21 14:09 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +        .keys       ( tm_keys       ),
Тут можно прямо написать .ledr (switches) так как мы передаем на led текущее состояние switches.
Кстати, почему он ledr а не led? (Надо подумать и возможно переименовать)

2024-09-21 14:10 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +        .w_digit ( w_digit )        // fake parameter, digit count is hardcode in tm1638_board_controller
Если он fake, то его не нужно передавать, он все равно стоит 8 по умолчанию в модуле. То есть лишний текст.

2024-09-21 14:10 UTC, yuri-panchul requested changes
См. комменты

2024-09-21 14:14 UTC, yuri-panchul commented
> Исправил проблемы компиляции модуля. Так же обнаружил, что в плате `de10_lite_tm1638_arduino` убрали модуль tm1638

А, я совсем забыл что эту конфигурацию я собирался для вас использовать. Ну сделайте новую конфигурацию de10_lite_with_extra_tm1638_switches

2024-09-21 14:17 UTC, unaimillan commented
Ещё одна проблема этой конфигурации — GPIO пины [27], [29], [31] пересекаются у i2s_audio_out и tm1638

2024-09-21 14:32 UTC, unaimillan reviewed
Все комментарии исправлены

2024-09-21 14:36 UTC, unaimillan reviewed
.

2024-09-21 15:32 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
> +    logic [ w_key - 1:0] tm_keys_r;
Все вроде нормально, но tm_keys можно везде заменить на keys. Тут из контекста понятно что это keys от tm. Хотя если не совсем понятно, можно оставить и так - up to you

2024-09-21 15:33 UTC, yuri-panchul commented on peripherals/tm1638_switch.sv
>  module tm1638_switch
Может заменить название модуля на tm1638_virtual_switches для понятности?

2024-09-21 15:37 UTC, yuri-panchul approved these changes
Можно сделать еще пару изменений, но пока приму . Вы можете сделать отдельную конфигурацию чтобы все работало на плате? И пример к ней? Скажем ввод 16-битного числа (8 бит с switches на DE10-Lite и 8 бит с tm1638 по кнопке на DE10-Lite с выводом зафиксированного числа на 7-сегментный индикатор

2024-09-21 15:37 UTC, merged