Draft: Virtual tm1638
yuri-panchul/basics-graphics-music pull request #176
Opened 2024-10-10 22:33 UTC by anton-malakhov

Adding HDMI visualization of virtual tm1638 board. It helps to do 7 segments tasks with just single simplest FPGA board.

NOTICE: Daft! This is my first Verilog design ever. Also, the logic for registered and masked indicators is not yet finished.

2024-10-11 03:52 UTC, yuri-panchul requested changes
Я почитал, и у меня предложение сделать это по другому. Во-первых, сделать не "или HDMI - или virtual tm1638", а их совместить и нарисовать виртуальный TM1638 на графическом дисплее с помощью операции XOR. Тогда на белом фоне цифры виртуального TM1638 будут черными, на черном фоне - белыми, на красном - зелеными, на оранжевом - синими.

То есть если у нас есть два источника цвета, lab_top и virtual_tm1638_using_graphics, то можно сделать это так:

lab_top
...
i_lab_top
(
   ....
   .red     (lab_red),
   .green (lab_green),
...
);

wire [w_red    - 1:0] vtm_red;
wire [w_green - 1:0] vtm_green;

`ifdef INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE
    assign vtm_red = '0;
    assign vtm_green = '0;
`else
    virtual_tm1638_using_graphics
    ...
    i_vtm
    (
       ....
       .red     (vtm_red),
       .green (vtm_green),
    ...
    );
`endif

wire [w_red     - 1:0] red     = lab_red     ^ vtm_red;
wire [w_green - 1:0] green = lab_green ^ vtm_green;

Обращаю внимание, что при таком подходе нам вообще не нужно вводить новых препроцессорных символов. Если TM1638 есть -  используется он, если его нет, но разрешена графика - на графическом экране слева вверху появляется виртуальный TM1638. Причем если лаба его не использует (игра) то он не высвечивается

При этом, то что я написал выше можно еще и оптимизировать. Вместо выводов vtm_red, vtm_green, vtm_blue из virtual_tm1638_using_graphics можно сделать однобитовый вывод pixel, после чего написать:

wire [w_red     - 1:0] red     = lab_red     ^ { w_red { pixel } };
wire [w_green - 1:0] green = lab_green ^ { w_red { pixel } };

У меня еще несколько более мелких предложений, но давайте мы это приведем в законченный вид итеративно, сначала вот это

2024-10-11 07:18 UTC, anton-malakhov commented
Всё-таки не так просто не вводить новые сущности тут. Есть `FORCE_NO_INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE` которая андефит `INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE` - тогда не понятно надо делать виртуальный модуль или нет. Но видимо стоит заменить все форсы на мой макрос эмуляции. Это так же поможет решить куда привязывать кнопки

2024-10-11 22:33 UTC, yuri-panchul commented
Ну я же написал выше: виртуальный модуль делается тогда и только тогда когда нет реального:

ifdef INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE

// Есть реальный, нет виртуального 
assign vtm_red = '0;
assign vtm_green = '0;

else

// Есть виртуальный, нет реального
virtual_tm1638_using_graphics

*** Есть FORCE_NO_INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE которая андефит INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE - тогда не понятно надо делать виртуальный модуль или нет.  ***

Да, делать однозначно. FORCE говорит что физический TM не подключен, то есть на физических проводах от него - мусорные значения X, их нельзя использовать например для reset.

Графика при этом может быть - с реальными кнопками на плате. И вот тогда нужно инстанциировать виртуальный.

*** Но видимо стоит заменить все форсы на мой макрос эмуляции.  ***

А если пользователь захочет вообще отключить графику (и обычную, и виртуальный TM1638), а также отключить реальный TM1638 и использовать только реальные кнопки на самой плате и GPIO? С моими макросами он может это сделать, а ваш макрос тут лишняя сужность, так как он включит графику, которую пользователь не хочет.

2024-10-12 20:29 UTC, anton-malakhov commented
Хорошо, репозиторий ваш, спорить не буду - сделаю как скажете (disagree & commit как говорят американцы). Но давайте сначала предположим что мы делаем это существующими макросами. Меня больше беспокоит не то когда мы явно хотим отключить графику, а то чтобы кнопки и светодиоды на HDMI были включены c самой первой лабы, которая графику не включает. Тогда получается, что я хотел бы поставить `define INSTANTIATE_GRAPHICS_INTERFACE_MODULE` для всех no_tm1638 конфигураций, но это уже противоречит желанию отключить графику вообще (там же `ifdef` а не `if`) - потому что как я понимаю конфиги читаются до board_specific_top.. Получается придётся вводить макрос типа FORCE_NO_GRAPHICS..
Ну а когда лаба включает графику с намерением рисовать что-то на экране (игра?) и не желает использовать tm1638 ни реальный, ни виртуальный - по макросам (`FORCE_NO_INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE` и `INSTANTIATE_GRAPHICS_INTERFACE_MODULE`) получается как раз ситуация когда виртуальный включится, будет мешаться своими прямоугольниками на экране и отключить его средств не будет. Может я что-то упускаю?

2024-10-13 06:41 UTC, yuri-panchul commented
> Хорошо, репозиторий ваш, спорить не буду - сделаю как скажете (disagree & commit как говорят американцы). Но давайте сначала предположим что мы делаем это существующими макросами. Меня больше беспокоит не то когда мы явно хотим отключить графику, а то чтобы кнопки и светодиоды на HDMI были включены c самой первой лабы, которая графику не включает. Тогда получается, что я хотел бы поставить `define INSTANTIATE_GRAPHICS_INTERFACE_MODULE` для всех no_tm1638 конфигураций, но это уже противоречит желанию отключить графику вообще (там же `ifdef` а не `if`) - потому что как я понимаю конфиги читаются до board_specific_top.. Получается придётся вводить макрос типа FORCE_NO_GRAPHICS.. Ну а когда лаба включает графику с намерением рисовать что-то на экране (игра?) и не желает использовать tm1638 ни реальный, ни виртуальный - по макросам (`FORCE_NO_INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE` и `INSTANTIATE_GRAPHICS_INTERFACE_MODULE`) получается как раз ситуация когда виртуальный включится, будет мешаться своими прямоугольниками на экране и отключить его средств не будет. Может я что-то упускаю?

Антон, чтобы не разводить дискуссию с 3 страницами обсуждения логики использования, я предлагаю вам участвовать в созвоне который будет в воскресенье 13 октября 2024, в 10.00 по Калифорнии (летнее время), 20.00 по Москве

http://bit.ly/yuri-panchul-zoom
https://zoom.us/j/5412567027?pwd=MnVqb05uR2NDM0N1QmltWTZRTnQzdz09

Это будет быстрее.

Теперь тезисно:

1. Текущая логика использования предполагает, что пользователь не будет копаться в `define никогда. `define и конфиги - только для удобства разработчиков, поддерживающих платы и примеры. Пользователь выбирает конфигурацию на основе того, что у него есть (плата, экран и TM1638) и после этого все делается автоматически.

2. Единственная причина существования NO_TM1638 конфигураций - это случай когда пользователь купил плату, на которой нет 7-сегментного индикатора или он узкий (2 или 3 цифры), и при этом у пользователя в городе нет магазина с TM1638 или заказ с АлиЭкспресса будет идти месяц, и при этом пользователь прямо сейчас хочет делать какие-нибудь примеры, например с двумя кнопками и шестью LED на плате запускать графические игры и упражнения с сдвиговым регистром и двоичным счетчиком.

Наличие вашего виртуального TM1638 позволит ему расширить примеры до процессора и FIFO, что важно.

3. Главная причина отключить графику вообще - это если пользователь купил совсем маленькую плату (Tang Nano 1K или вообще с MAXII и хочет запустить что-то совсем скромное, типа арбитра, но с графикой это не влазит. Или влазит, но он хочет уменьшить время синтеза (вторая причина). В случае вашего виртуального TM1638 графику выключать нельзя даже в первой лабе, потому что на некоторых платах есть только одна кнопка и одна лампочка функциональность TM1638.

4. Если рисовать ваш виртуальный TM1638 с помощью xor на экране, то он не будет мельтешить, так как виртуальные LED и 7-сегментные индикаторы просто не будут загораться напрмер в графической игре. Поэтому нет ничего плохого если он будет всегда, когда не подключен реальный TM1638 и есть графика. Мельтешить может только отображение нажимаемых кнопок, но этого можно не делать.

5. Использовать конфигурацию с TM1638 когда его физически нет (не подключены провода) - нельзя, потому что многие платы используют с его кнопки сброс, и когда его физически нет, на этом проводе находится плавающее значение (нии 0, ни 1), и дизайн просто глючит.

FORCE_NO_INSTANTIATE_TM1638_BOARD_CONTROLLER_MODULE - связано именно с последним случаем, а не с желанием пользователя упростить текущий синтез без TM1638.

Короче, я несколько утерял нить дискуссии. Давайте обсудим на созвоне. Вы хотите сделать еще один `define VIRTUAL_TM1638? А зачем? Чтобы `define графику если она undefined? Так она сейчас по умолчанию defined

2024-10-13 14:23 UTC, anton-malakhov commented on labs/1_basics/1_05_7seven_segment_letter/lab_specific_board_config.svh
> -   `define INSTANTIATE_GRAPHICS_INTERFACE_MODULE
forgot to remove it - will change in the next iteration

2024-10-13 15:26 UTC, yuri-panchul commented on boards/tang_nano_9k_hdmi_tm1638/board_specific_top.sv
> +    wire  [w_red       - 1:0] red   =   lab_red ^ { w_red   { inv_red } };
А зачем называет его inv_? XOR инвертирует только в последнем случае, а в трех первых рисует или не рисует:

0 ^ 0 = 0 - отсутствие цвета на отсутствии цвета дает отсутствие цвета
0 ^ 1 = 1 - присутствие цвета на отсутствии цвета дает присутствие цвета (виртуального TM)
0 ^ 1 = 1 - отсутствие цвета на присутствии цвета дает присутствие цвета (фона)
1 ^ 1 = 0 - присутствие цвета на присутствии цвета (цветной фон) дает отсутствие цвета (белый на черном например)

Давайте назовем vtm_red (virtual tm).
И почему не один пиксел? Вы хотите сделать изображение tm многоцветным с градациями? Или это на будущее?

2024-10-13 15:34 UTC, anton-malakhov commented on boards/tang_nano_9k_hdmi_tm1638/board_specific_top.sv
> +    wire  [w_red       - 1:0] red   =   lab_red ^ { w_red   { inv_red } };
Инвертирую компонент цвета из лабы. Хорошо, переименую. Да, с цветом как-то веселее, да и "светодиоды" от сегментов отделяет - см. в группе видео. Пространственно не хотелось раздувать конструкцию или формулу сегментов менять

2024-10-13 15:38 UTC, yuri-panchul commented on peripherals/tm1638_virtual_shadow.sv
> +        cx = (x-offsetx) / clenx;
Возможно стоит заменить на ">> clenx_shift" и определить "localparam clenx_shift = $clog2 (clenx)". Так как теоретически может быть синтезатор, который не оптимизирует деление на степень двойки и вставляет комбинационное деление, которое является сверх-тяжелой операцией для тайминга внутри такта. Поэтому делений даже на константу стоит избегать, даже степени двойки, стоит избегать когда в этом нет необходимость. Но тут, пользуясь случаем, вы можете проверить, во что превращает такое деление синтезатор и сравнить его с делением на другие константы и не-константы (это хорошее упражнение для изучения static timing analysis)

2024-10-13 15:39 UTC, yuri-panchul approved these changes
inv_ стоит поменять (имя может сбить с толку). Про defines еще можно обсудить, но пока так нормально

2024-10-13 15:47 UTC, anton-malakhov commented on peripherals/tm1638_virtual_shadow.sv
> +        cx = (x-offsetx) / clenx;
хорошо. да, оно работает у меня для размера cell = 9
жду когда будем этот анализ изучать :)

2024-10-13 15:59 UTC, yuri-panchul commented
Я также предлагаю поменять название файла tm1638_shadow_virtual.sv на virtual_tm1638_using_graphics.sv Так как словом shadow (например shadow memory или shadow registers) обычно называют объекты, которые стоят впридачу к основным, повторяя примененные к оригиналам действия для тех или иных целей (например учет транзакций для проверки соображения тайминга после размещения крупных компонент). А у нас tm и virtual tm по текущему дизайну исключают друг друга (virtual используется пока не дошел с aliexpress реальный)

2024-10-13 16:05 UTC, anton-malakhov commented
Да, вот это тоже этот же вопрос. Я хотел сделать как дублирующий индикатор для TM1638, который работает и без него. Ок, переименую

2024-10-13 16:24 UTC, anton-malakhov commented
надо порядок индикаторов, а заодно и всего остального поменять, а то примеры со счётчиком и словом не в ту сторону работают

2024-10-13 17:03 UTC, yuri-panchul commented
Отчет по таймингу можно получить вот здесь. Ключевой параметр - slack - сколько остается времени в такте в наносекундах. Если slack отрицательный - будет глючить или работать случайно (например из-за более медленного pixel clock). Сейчас slack померять корректно невозможно, так как выходная логика не заканчивается на регистре (дефект текущего дизайна). Если поставить в конце логики регистр, то стоит провести три эксперимента с делением: без него, с делением на 8 и делением на 9 - как это повлияет на slack

![image](https://github.com/user-attachments/assets/1ccccde6-4fbd-43e9-b3da-33ee4bfa72ff)

2024-10-13 20:29 UTC, anton-malakhov commented
Только Tang Nano 9K проверен и включён. Так же было бы здорово если подскажите как убрать дублирование кода в generate блоке

2024-10-15 00:45 UTC, yuri-panchul commented on labs/2_graphics/2_4_game/game_config.svh
> +`define FORCE_NO_VIRTUAL_TM1638_USING_GRAPHICS
This header file is not used in board_specific_top.sv (or should not be used), this is a lab-specific file

2024-10-15 00:47 UTC, yuri-panchul commented on peripherals/tm1638_using_graphics.sv
> +    assign c_hex[0] = digit [0] ? abcdefgh : '0;
This can be improved with a generate for:

2024-10-15 00:48 UTC, yuri-panchul commented on peripherals/tm1638_using_graphics.sv
> +    assign hex[0] = static_hex ? r_hex[0] : c_hex[0];
This can be improved with generate for

2024-10-15 00:50 UTC, yuri-panchul approved these changes
I am going to accept this, but two issues should be addressed:

1. game_config is not the right file for that define
2. put generate into the peripheral file

2024-10-15 00:50 UTC, merged