Lab waveform generator
yuri-panchul/basics-graphics-music pull request #211
Opened 2024-12-30 12:56 UTC by oVadim

Предварительная версия, кнопки 1, 2, 3. Символы S, t, q.

2025-01-01 23:34 UTC, yuri-panchul commented on labs/3_music/3_7_waveform_generator/lab_top.sv
> +    wire [23:0] sound_24 = { sound [15:0], { 8 { 1'b0 } } };
Это эквивалентно 
wire [23:0] sound_24 = { sound [15:0], 8'b0 };

2025-01-01 23:34 UTC, yuri-panchul commented on labs/3_music/3_7_waveform_generator/lab_top.sv
> +    wire  [w_key   - 1:0] waveform   = key;
Нужно выравнивание по пробелам

2025-01-01 23:36 UTC, yuri-panchul commented on labs/3_music/3_7_waveform_generator/lab_top.sv
> +    assign digit = { {(w_digit - 1){1'b0}}, 1'b1};
(w_digit - 1) - скобки не нужны
Также это эквивалентно 
assign digit =  w_digit' (1);

2025-01-01 23:38 UTC, yuri-panchul commented on labs/3_music/3_7_waveform_generator/oscilloscope.sv
> +    input                        uart_rx,
uart_* и gpio здесь лишние сигналы - они не используются. Их нужно убрать из модуля

2025-01-01 23:41 UTC, yuri-panchul requested changes
См. комменты выше. Некоторые некритичны, но лишние сигналы нужно убрать перед merge

2025-01-01 23:41 UTC, yuri-panchul commented on labs/3_music/3_7_waveform_generator/oscilloscope.sv
> +    output                       uart_tx,
Лишние сигналы нужно убрать перед merge

2025-01-02 05:02 UTC, oVadim commented
Всё сделал

2025-01-07 16:43 UTC, yuri-panchul commented on boards/tang_primer_20k_dock_hdmi_tm1638/board_specific_top.sv
> +    output                      SCK,
Этих пинов нет в boards/tang_primer_20k_dock_hdmi_tm1638/board_specific.cst
Откуда они в списке output портов? Это провода которые должны присоединяться к GPIO, правильно?

2025-01-07 16:45 UTC, yuri-panchul commented on boards/tang_primer_20k_dock_hdmi_tm1638/board_specific_top.sv
> +    /*(
Что означает это комментарий? Его удалять или нет?

2025-01-07 16:47 UTC, yuri-panchul commented on boards/tang_primer_20k_dock_lcd_800_480_tm1638/board_specific_top.sv
> +    /*(
Этот коммент нужно или убрать или объяснить

2025-01-07 16:48 UTC, yuri-panchul commented on boards/tang_primer_20k_dock_no_hdmi_no_tm1638/board_specific.cst
> +// Sipeed R6+1 Microphone Array Board in GPIO connector
Почему это должно быть закомментарено?

2025-01-07 16:53 UTC, yuri-panchul approved these changes
Хорошо, это я принимаю - см. мелкие комментарии

2025-01-07 16:53 UTC, merged

2025-01-07 17:03 UTC, oVadim commented on boards/tang_primer_20k_dock_hdmi_tm1638/board_specific_top.sv
> +    /*(
Это касается того 6+1 микрофона с RGB светодиодами, который мы купили (есть ещё у пары человек). Основным вариантом я выбрал или 441 микрофон (схему приложил) или родной Pmod совместимый микрофон от Sipeed (по цене почти как 441). У 6+1 микрофона пины другие (на том же самом Pmod0. Поэтому при его применении надо его раскомментировать и закомментировать одиночный микрофон. Когда я привёл нумерацию GPIO к стандарту Pmod получилось, что я не могу произвольно переставить пины, поэтому я ввёл закомментированную часть в коде с другими пинами. Я сделаю так: все закомментированные части я уберу из sv и cst, а для 6+1 микрофона сделаю альтернативную конфигурацию. Но тут будет слишком много конфигураций, может сделать только для варианта LCD 800x600 c TM1638?

2025-01-07 17:06 UTC, oVadim commented on boards/tang_primer_20k_dock_hdmi_tm1638/board_specific_top.sv
> +    output                      SCK,
Я забыл там их удалить. Внешнему ЦАП я назначил пины GPIO согласно нумерации Pmod. Сейчас удалю на вв 2 файлах.

2025-01-07 17:08 UTC, oVadim commented on boards/tang_primer_20k_dock_no_hdmi_no_tm1638/board_specific.cst
> +// Sipeed R6+1 Microphone Array Board in GPIO connector
Вариант расстановки пинов для Sipeed R6+1 Microphone Array Board

2025-01-07 17:15 UTC, oVadim commented on labs/3_music/3_3_note_synthesizer/surfer.bash
> +#!/usr/bin/env bash
Мне показался вариант с открытием по умолчанию gtkwave (windows например) удобнее, так как он более конфигурируемый, я нашёл примеры конфигурации (много параметров). У surfer из полезного только добавление сигналов. Высота строки не увеличивается, аналогового вида не нашёл. Я поэтому сделал такой вариант: если надо - открываем surfer. В главном скрипте всё нашёл, но не определил, когда нам нужно его вызывать (ос и т.д.).